### ISSUE TITLE
Peer to Peer code review

### ISSUE THREAD

**Issue by hassanShakur** [marvin-nyalik/NyalikPortfolio#7]
Fantastic job on the portfolio. The implementation is as close to the design as it could possibly get ✅. Just a minor correction, it is always best in terms of user experience to use the `placeholder` property in place of the `value` property for the `input` elements. This way the user won't have to delete the input default value before typing their response. Other than that, good job 😄.

**Comment by ticoniq** [comment]
You have done a nice on your portfolio. This implementation is close to the design. for best HTML practice I think it's better to remove the logo, mobile nav icon, and div from the `ul tag`  to make the browser quickly understands that it is a navigation menu

**Comment by Fombi-Favour** [comment]
Great job on this portfolio 👍✅. Every design element matches that of the figma design 🎉. I think its better to use a `div` tag on the `section` tag instead of the `article` tag
